import { Mentor } from './types';

export const mentorsData: Mentor[] = [
  {
    id: 1,
    name: "Sarah Johnson",
    image: "https://images.unsplash.com/photo-1494790108755-2616b612b789?w=400&h=400&fit=crop&crop=face",
    expertise: "Full Stack Developer",
    bio: "10+ years building scalable web applications with React, Node.js, and cloud technologies. Passionate about mentoring junior developers.",
    fullBio: "With over a decade of experience in full-stack development, I've worked with startups and Fortune 500 companies to build scalable web applications. My expertise spans modern JavaScript frameworks, cloud architecture, and DevOps practices. I'm passionate about mentoring the next generation of developers and helping them navigate their career paths.",
    rating: 4.9,
    students: 156,
    specialties: ["React", "Node.js", "AWS", "TypeScript", "GraphQL", "MongoDB"],
    experience: "10+ years",
    location: "San Francisco, CA",
    hourlyRate: 120,
    languages: ["English", "Spanish"],
    availability: ["Mon-Fri 9AM-6PM PST", "Weekend sessions available"],
    achievements: ["AWS Certified Solutions Architect", "React Conf Speaker 2023", "Tech Lead at Meta"]
  },
  {
    id: 2,
    name: "Dr. Michael Chen",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
    expertise: "AI/ML Specialist",
    bio: "PhD in Computer Science with expertise in machine learning, deep learning, and AI ethics. Former Google AI researcher.",
    fullBio: "As a former Google AI researcher with a PhD in Computer Science from Stanford, I specialize in machine learning, deep learning, and ethical AI development. I've published over 50 research papers and hold 12 patents in AI technology. My goal is to make AI accessible and help others understand its potential and limitations.",
    rating: 4.8,
    students: 203,
    specialties: ["Python", "TensorFlow", "PyTorch", "Data Science", "NLP", "Computer Vision"],
    experience: "12+ years",
    location: "Mountain View, CA",
    hourlyRate: 180,
    languages: ["English", "Mandarin", "Cantonese"],
    availability: ["Flexible schedule", "International sessions welcome"],
    achievements: ["PhD Stanford", "Ex-Google AI", "50+ Research Papers", "AI Ethics Committee Member"]
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face",
    expertise: "UX/UI Designer",
    bio: "Award-winning designer with 8 years creating user-centered experiences for Fortune 500 companies and innovative startups.",
    fullBio: "I'm a passionate UX/UI designer with 8 years of experience creating intuitive and beautiful digital experiences. I've worked with companies like Apple, Airbnb, and Netflix to design products used by millions. I believe great design is invisible and focuses on solving real user problems.",
    rating: 4.9,
    students: 127,
    specialties: ["Figma", "Design Systems", "User Research", "Prototyping", "Accessibility", "Mobile Design"],
    experience: "8+ years",
    location: "New York, NY",
    hourlyRate: 140,
    languages: ["English", "Spanish", "Portuguese"],
    availability: ["Mon-Thu 10AM-7PM EST", "Friday mornings"],
    achievements: ["Design Award Winner 2023", "Ex-Apple Design", "Figma Community Leader", "IXDA Member"]
  },
  {
    id: 4,
    name: "James Wilson",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    expertise: "DevOps Engineer",
    bio: "Cloud infrastructure expert specializing in Kubernetes, Docker, and CI/CD pipelines. Helped scale systems to millions of users.",
    fullBio: "I'm a DevOps engineer with extensive experience in cloud infrastructure, container orchestration, and automation. I've helped companies scale their systems from thousands to millions of users while maintaining 99.99% uptime. I love sharing knowledge about modern DevOps practices and cloud-native technologies.",
    rating: 4.7,
    students: 89,
    specialties: ["Kubernetes", "Docker", "AWS", "Terraform", "Jenkins", "Monitoring"],
    experience: "9+ years",
    location: "Austin, TX",
    hourlyRate: 130,
    languages: ["English"],
    availability: ["Tue-Sat flexible hours", "Emergency weekend support"],
    achievements: ["AWS Solutions Architect Pro", "Kubernetes Certified", "DevOps Institute Ambassador"]
  },
  {
    id: 5,
    name: "Priya Sharma",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face",
    expertise: "Mobile App Developer",
    bio: "React Native and Flutter specialist with 50+ published apps. Expert in cross-platform development and app store optimization.",
    fullBio: "I'm a mobile app developer with expertise in React Native and Flutter. I've published over 50 apps on both iOS and Android platforms, with several reaching the top charts. My focus is on creating performant, user-friendly mobile experiences and helping others master cross-platform development.",
    rating: 4.8,
    students: 174,
    specialties: ["React Native", "Flutter", "iOS", "Android", "App Store Optimization"],
    experience: "7+ years",
    location: "Seattle, WA",
    hourlyRate: 115,
    languages: ["English", "Hindi"],
    availability: ["Mon-Fri 8AM-5PM PST", "Weekend consultations"],
    achievements: ["50+ Published Apps", "Google Developer Expert", "React Native Core Contributor"]
    },
    {
    id: 6,
    name: "David Kim",
    image: "https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=400&h=400&fit=crop&crop=face",
    expertise: "Cybersecurity Expert",
    bio: "Ethical hacker and security consultant with CISSP certification. Specializes in penetration testing and security architecture.",
    fullBio: "As a cybersecurity expert with over 8 years of experience, I specialize in ethical hacking, penetration testing, and security architecture. I hold multiple certifications including CISSP and CEH, and have helped organizations secure their infrastructure against evolving threats.",
    rating: 4.9,
    students: 98,
    specialties: ["Penetration Testing", "Security Auditing", "Compliance", "Risk Assessment", "Ethical Hacking"],
    experience: "8+ years",
    location: "Washington, DC",
    hourlyRate: 150,
    languages: ["English", "Korean"],
    availability: ["Mon-Fri 9AM-6PM EST", "Emergency security consultations"],
    achievements: ["CISSP Certified", "CEH Master", "Security Conference Speaker", "Published Security Researcher"]
    },
    {
    id: 7,
    name: "Lisa Thompson",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face",
    expertise: "Product Manager",
    bio: "Strategic product leader with experience launching products that generated $100M+ revenue. Expert in agile methodologies and user analytics.",
    fullBio: "I'm a strategic product manager with over 9 years of experience launching successful products. I've worked at companies like Spotify and Uber, managing products that generated over $100M in revenue. I'm passionate about user-centered design and data-driven product decisions.",
    rating: 4.8,
    students: 142,
    specialties: ["Product Strategy", "Agile", "Analytics", "User Research", "Roadmapping"],
    experience: "9+ years",
    location: "Los Angeles, CA",
    hourlyRate: 135,
    languages: ["English", "French"],
    availability: ["Tue-Thu 10AM-7PM PST", "Monday evening sessions"],
    achievements: ["$100M+ Product Revenue", "Ex-Spotify PM", "Agile Certified", "Product Management Institute Fellow"]
    },
    {
    id: 8,
    name: "Ahmed Hassan",
    image: "https://images.unsplash.com/photo-1556157382-97eda2d62296?w=400&h=400&fit=crop&crop=face",
    expertise: "Blockchain Developer",
    bio: "Blockchain architect with deep expertise in Ethereum, Solidity, and DeFi protocols. Built multiple successful dApps and smart contracts.",
    fullBio: "I'm a blockchain developer and architect with deep expertise in Ethereum, Solidity, and DeFi protocols. I've built multiple successful dApps and smart contracts that have processed millions in transactions. My passion is making blockchain technology accessible and secure for everyone.",
    rating: 4.7,
    students: 76,
    specialties: ["Solidity", "Web3", "Smart Contracts", "DeFi", "Ethereum", "dApp Development"],
    experience: "6+ years",
    location: "Dubai, UAE",
    hourlyRate: 160,
    languages: ["English", "Arabic"],
    availability: ["Sun-Thu 9AM-6PM GST", "Global timezone flexibility"],
    achievements: ["50+ Smart Contracts Deployed", "DeFi Protocol Architect", "Ethereum Foundation Grant Recipient"]
    }
];